// examples/angular/angular-examples.ts
// @ts-nocheck
/**
 * AsyncFlowState - Angular Examples
 * 
 * Demonstrates how to use @asyncflowstate/angular factories with RxJS.
 */
import { Component, OnDestroy } from '@angular/core';
import { AsyncPipe, NgIf, NgFor } from '@angular/common';
import { 
  createFlow, 
  createFlowSequence, 
  createFlowList 
} from '@asyncflowstate/angular';

@Component({
  selector: 'app-examples',
  standalone: true,
  imports: [AsyncPipe, NgIf, NgFor],
  template: `
    <div class="examples">
      
      <!-- Example 1: Basic Flow -->
      <section *ngIf="userFlow.state$ | async as state">
        <h2>Basic BehaviorSubject Fetching</h2>
        
        <button (click)="userFlow.execute('123')" [disabled]="state.loading">
          {{ state.loading ? 'Fetching...' : 'Load User' }}
        </button>
        
        <div *ngIf="state.data">
          <p>Name: {{ state.data.name }}</p>
        </div>
        <div *ngIf="state.error" class="error">
          {{ state.error.message }}
        </div>
      </section>

      <!-- Example 2: Keyed List execution -->
      <section *ngIf="deleteFlow.state$ | async as listState">
        <h2>List Executions (No global blocking)</h2>
        <ul>
          <li *ngFor="let item of items">
            {{ item.name }}
            <button 
              (click)="deleteFlow.execute(item.id, item.id)"
              [disabled]="listState.states[item.id]?.status === 'loading'">
              {{ listState.states[item.id]?.status === 'loading' ? 'Deleting...' : 'Delete' }}
            </button>
          </li>
        </ul>
      </section>

      <!-- Example 3: Sequence -->
      <section *ngIf="sequence.state$ | async as seqState">
        <h2>Sequence Orchestration</h2>
        <button (click)="sequence.execute()" [disabled]="seqState.loading">
          Run Sequence ({{ seqState.progress }}%)
        </button>
        <p *ngIf="seqState.currentStep">Running: {{ seqState.currentStep.name }}</p>
      </section>

    </div>
  `,
  styles: [`
    .error { color: red; font-size: 0.8em; }
    section { margin-bottom: 2rem; padding: 1rem; border: 1px solid #ccc; }
  `]
})
export class ExamplesComponent implements OnDestroy {
  // 1. Basic Flow
  userFlow = createFlow(
    async (id: string) => {
      const res = await fetch(`/api/users/${id}`);
      if (!res.ok) throw new Error('User not found');
      return res.json();
    },
    { retry: { maxAttempts: 3 } }
  );

  // 2. Flow List
  deleteFlow = createFlowList(
    async (id: string) => {
      await new Promise(resolve => setTimeout(resolve, 1000));
    }
  );
  items = [{ id: '1', name: 'Item 1' }, { id: '2', name: 'Item 2' }];

  // 3. Flow Sequence
  sequence = createFlowSequence([
    { name: 'Auth', flow: this.userFlow.flow },
    { 
      name: 'Fetch Data', 
      flow: createFlow(async () => { /* another task */ }).flow 
    }
  ]);

  ngOnDestroy() {
    // Cleanup subscriptions and flow instances
    this.userFlow.destroy();
    this.deleteFlow.destroy();
    this.sequence.destroy();
  }
}

// examples/vue/vue-examples.vue
<script setup lang="ts">
/**
 * AsyncFlowState - Vue Examples
 * 
 * Demonstrates how to use @asyncflowstate/vue composables.
 */
import { ref } from 'vue';
import { useFlow, useFlowSequence, useFlowParallel, provideFlowConfig } from '@asyncflowstate/vue';
import { z } from 'zod';

// =============================================================================
// Example 1: Global Config Setup (Root Component Level)
// =============================================================================
provideFlowConfig({
  retry: { maxAttempts: 2, backoff: 'exponential' },
  loading: { minDuration: 300 }, // Prevent UI flickering
});

// =============================================================================
// Example 2: Basic Data Fetching
// =============================================================================
const fetchUserFlow = useFlow(
  async (id: string) => {
    const res = await fetch(`/api/users/${id}`);
    if (!res.ok) throw new Error('User not found');
    return res.json();
  },
  {
    onSuccess: (user) => console.log('User loaded:', user),
  }
);

// =============================================================================
// Example 3: Form Handling with Zod Validation
// =============================================================================
const formSchema = z.object({
  email: z.string().email('Invalid email address'),
  password: z.string().min(6, 'Password too short'),
});

const loginFlow = useFlow(
  async (data: any) => {
    // API Call
    await new Promise(resolve => setTimeout(resolve, 800));
    return { token: 'xyz' };
  }
);

// =============================================================================
// Example 4: Sequential Workflow
// =============================================================================
const sequence = useFlowSequence([
  { name: 'Validate', flow: loginFlow.flow }, // Link to existing flow
  { 
    name: 'Fetch Profile', 
    flow: fetchUserFlow.flow,
    mapInput: (prevResult) => prevResult?.token // Pipe result to next step
  }
]);

</script>

<template>
  <div class="examples">
    
    <!-- Example 2 UI -->
    <section>
      <h2>Basic Data Fetching</h2>
      <button v-bind="fetchUserFlow.button()" @click="fetchUserFlow.execute('123')">
        {{ fetchUserFlow.loading ? 'Fetching...' : 'Load User' }}
      </button>
      
      <div v-if="fetchUserFlow.data">
        <p>Name: {{ fetchUserFlow.data.name }}</p>
      </div>
      <div v-if="fetchUserFlow.error" class="error">
        {{ fetchUserFlow.error.message }}
      </div>
    </section>

    <!-- Example 3 UI -->
    <section>
      <h2>Form Validation</h2>
      <form v-bind="loginFlow.form({ schema: formSchema, extractFormData: true })">
        <div>
          <label>Email</label>
          <input name="email" type="email" />
          <span class="error" v-if="loginFlow.fieldErrors.email">
            {{ loginFlow.fieldErrors.email }}
          </span>
        </div>
        
        <div>
          <label>Password</label>
          <input name="password" type="password" />
          <span class="error" v-if="loginFlow.fieldErrors.password">
            {{ loginFlow.fieldErrors.password }}
          </span>
        </div>

        <button type="submit" :disabled="loginFlow.loading">
          {{ loginFlow.loading ? 'Logging in...' : 'Login' }}
        </button>
      </form>
    </section>

    <!-- Example 4 UI -->
    <section>
      <h2>Sequence Workflow</h2>
      <button @click="sequence.execute()" :disabled="sequence.loading">
        Run Async Sequence ({{ sequence.progress }}%)
      </button>
      <p>Current Step: {{ sequence.currentStep?.name || 'Idle' }}</p>
    </section>

  </div>
</template>

<style scoped>
.error { color: red; font-size: 0.8em; }
section { margin-bottom: 2rem; padding: 1rem; border: 1px solid #ccc; }
</style>
