// examples/svelte/svelte-examples.svelte
<script lang="ts">
/**
 * AsyncFlowState - Svelte Examples
 * 
 * Demonstrates how to use @asyncflowstate/svelte stores.
 */
import { 
  createFlow, 
  createFlowSequence, 
  createFlowList,
  createInfiniteFlow
} from '@asyncflowstate/svelte';

// =============================================================================
// Example 1: Basic Data Fetching
// =============================================================================
const fetchUserFlow = createFlow(
  async (id: string) => {
    const res = await fetch(`/api/users/${id}`);
    if (!res.ok) throw new Error('User not found');
    return res.json();
  },
  {
    retry: { maxAttempts: 2 },
  }
);

// =============================================================================
// Example 2: List Operations (e.g. Delete Buttons)
// =============================================================================
const deleteList = createFlowList(async (id: string) => {
  await new Promise(resolve => setTimeout(resolve, 1000));
  console.log('Deleted', id);
});

const items = [{ id: '1', name: 'Item 1' }, { id: '2', name: 'Item 2' }];

// =============================================================================
// Example 3: Infinite Scrolling
// =============================================================================
const postsFlow = createInfiniteFlow(
  async (cursor: number) => {
    // Simulated API response
    return { data: ['post1', 'post2'], nextCursor: cursor + 1 };
  },
  {
    initialPageParam: 0,
    getNextPageParam: (lastPage) => lastPage.nextCursor > 3 ? null : lastPage.nextCursor
  }
);
</script>

<div class="examples">
  
  <!-- Example 1 UI -->
  <section>
    <h2>Basic Data Fetching</h2>
    <button 
      on:click={() => fetchUserFlow.execute('123')} 
      disabled={$fetchUserFlow.loading}
    >
      {$fetchUserFlow.loading ? 'Fetching...' : 'Load User'}
    </button>
    
    {#if $fetchUserFlow.data}
      <p>Name: {$fetchUserFlow.data.name}</p>
    {/if}
    {#if $fetchUserFlow.error}
      <p class="error">{$fetchUserFlow.error.message}</p>
    {/if}
  </section>

  <!-- Example 2 UI -->
  <section>
    <h2>List Tracking</h2>
    <ul>
      {#each items as item}
        <li>
          {item.name}
          <button 
            on:click={() => deleteList.execute(item.id, item.id)}
            disabled={$deleteList.states[item.id]?.status === 'loading'}
          >
            {$deleteList.states[item.id]?.status === 'loading' ? 'Deleting...' : 'Delete'}
          </button>
        </li>
      {/each}
    </ul>
  </section>

  <!-- Example 3 UI -->
  <section>
    <h2>Infinite Flow</h2>
    {#each $postsFlow.pages as page, i}
      <div class="page">
        Page {i}: {page.data.join(', ')}
      </div>
    {/each}

    {#if $postsFlow.hasNextPage}
      <button 
        on:click={() => postsFlow.fetchNextPage()} 
        disabled={$postsFlow.isFetchingNextPage}
      >
        {$postsFlow.isFetchingNextPage ? 'Loading More...' : 'Load More'}
      </button>
    {:else}
      <p>No more posts.</p>
    {/if}
  </section>

</div>

<style>
.error { color: red; font-size: 0.8em; }
section { margin-bottom: 2rem; padding: 1rem; border: 1px solid #ccc; }
</style>

// examples/solid/solid-examples.tsx
// @ts-nocheck
/**
 * AsyncFlowState - SolidJS Examples
 *
 * Demonstrates how to use @asyncflowstate/solid fine-grained primitives.
 */
import { Show, For } from "solid-js";
import {
  createFlow,
  createFlowList,
  createInfiniteFlow,
  FlowProvider,
} from "@asyncflowstate/solid";

// =============================================================================
// Example 1: Basic Reactive Data Fetching
// =============================================================================
export function BasicFetch() {
  const fetchUserFlow = createFlow(
    async (id: string) => {
      const res = await fetch(`/api/users/${id}`);
      if (!res.ok) throw new Error("User not found");
      return res.json();
    },
    { retry: { maxAttempts: 2 } },
  );

  return (
    <section>
      <h2>Basic SolidJS Signal Fetching</h2>
      <button
        onClick={() => fetchUserFlow.execute("123")}
        disabled={fetchUserFlow.loading()}
      >
        {fetchUserFlow.loading() ? "Fetching..." : "Load User"}
      </button>

      <Show when={fetchUserFlow.data()}>
        {(user) => <p>Name: {user().name}</p>}
      </Show>

      <Show when={fetchUserFlow.error()}>
        {(err) => <p style="color: red">{err().message}</p>}
      </Show>
    </section>
  );
}

// =============================================================================
// Example 2: Flow List (Individual Loading States)
// =============================================================================
export function ListTracking() {
  const items = () => [
    { id: "1", name: "Item 1" },
    { id: "2", name: "Item 2" },
  ];

  const deleteList = createFlowList(async (id: string) => {
    await new Promise((resolve) => setTimeout(resolve, 800));
  });

  return (
    <section>
      <h2>List Context Tracking</h2>
      <ul>
        <For each={items()}>
          {(item) => (
            <li>
              {item.name}
              <button
                onClick={() => deleteList.execute(item.id, item.id)}
                disabled={deleteList.getStatus(item.id).status === "loading"}
              >
                {deleteList.getStatus(item.id).status === "loading"
                  ? "Deleting..."
                  : "Delete"}
              </button>
            </li>
          )}
        </For>
      </ul>
    </section>
  );
}

// =============================================================================
// Example 3: Context Provider App Base
// =============================================================================
export function App() {
  return (
    <FlowProvider
      config={{
        loading: { minDuration: 300 }, // Global prevent UI flashing
        retry: { backoff: "exponential" },
      }}
    >
      <div class="examples">
        <BasicFetch />
        <ListTracking />
      </div>
    </FlowProvider>
  );
}
